apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TheLastNever/ArgoCd.git
    targetRevision: HEAD
    path: Config
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true