apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: ahmetyas/hello-world:v1.0
          ports:
            - containerPort: 8080
      env: 
        - name: hello
          valueFrom:
            configMapKeyRef:
              name: hello-world-configmap
              key: hello
---