apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world
spec:
  selector:
    app.kubernetes.io/instance: hello-world-application
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: http
  type: LoadBalancer